name: Setup Node and install deps
description: Checkout, setup Node, and install dependencies
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22.14.0
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
